// docs/EFFECTS.md, generated from the control table.
//
// The page is an enumeration — every stage, every group, every control and the
// fault it models — and an enumeration written by hand drifts. It had: source B
// listed as taking a webcam it cannot take, and the user guide beside it had a
// morph ceiling two settings short and a stab length quoted at the default as
// though it were the range. None of those are wrong in the code, and nothing
// caught any of them.
//
// So nobody writes this file. `src/ui/controls.ts` is already the source of
// truth the panel renders from — a pure data module whose only two imports are
// `import type`, which is why node can load it here with no build step and no
// loader. Every `help` string is written to the rule the panel needs anyway
// (say what breaks in the hardware, not what the picture looks like), which is
// the same rule this page wants.
//
// The argued half of the old page — the tours, the reasons, the things with no
// control behind them — moved to docs/FEATURES.md and is still written by hand.
// Splitting them is what lets this half be generated at all: prose that makes a
// point cannot come out of a table, and a table should not be retyped as prose.
//
// Run: pnpm effects, or `--check` to fail when the checked-in copy is stale.

// Loaded through vite rather than imported directly. `controls.ts` alone would
// import fine — its only two imports are `import type`, so node's type
// stripping handles it — but `modes.ts` imports `./clips` extensionless, the
// way every module in `src/` does, and that is vite's resolution rather than
// node's. Borrowing the app's own resolver is what keeps this script able to
// read any module in `src/`, instead of only the leaves that happen to have no
// value imports.
import { createServer } from 'vite'

import { execFileSync } from 'node:child_process'
import { readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'

const vite = await createServer({
  server: { middlewareMode: true },
  appType: 'custom',
  logLevel: 'error',
})
const load = p => vite.ssrLoadModule(p)

// The shipped lists rather than the raw ones: the page describes what a reader
// can actually reach, and YouTube is backed by a dev-only bridge.
const { SHIPPED_B_MODES, SHIPPED_MODES, SOURCE_DESC } = await load(
  '/src/sources/modes.ts',
)
const {
  GROUPS,
  LOOP_STAGES,
  PHASE_ORDER,
  SOUND_BLURB,
  SOUND_JOIN,
  SOUND_STAGE,
  VIEW_JOIN,
  VIEW_STAGE,
} = await load('/src/ui/controls.ts')

const OUT = 'docs/EFFECTS.md'

// Markdown table cells break on a raw pipe, and a few help strings carry one.
const cell = s => s.replaceAll('|', '\\|')

// A control's span, in the terms its own row shows. An enum has no span worth
// printing — its choices *are* the span — so it prints those instead.
const span = s => {
  if (s.choices !== undefined) {
    return s.choices.map(c => `\`${c}\``).join(' · ')
  }
  return `${s.min}–${s.max}${s.unit === '' ? '' : ` ${s.unit}`}`
}

const table = sliders =>
  [
    '| Control | Range | The fault it models |',
    '| --- | --- | --- |',
    ...sliders.map(
      s => `| **${cell(s.label)}** | ${cell(span(s))} | ${cell(s.help)} |`,
    ),
  ].join('\n')

const section = (heading, blurb, groups) =>
  groups.length === 0
    ? []
    : [
        `## ${heading}`,
        '',
        ...(blurb === undefined ? [] : [blurb, '']),
        ...groups.flatMap(g => [`### ${g.name}`, '', table(g.sliders), '']),
      ]

const at = place => GROUPS.filter(g => g.place === place)

// Each deck's own picker list, as the picker's own descriptions. The difference
// between the two lists is the fact the hand-written page got wrong, so it is
// stated here rather than left for a reader to diff.
const modeList = modes =>
  modes
    .filter(m => m !== 'none' && SOURCE_DESC[m] !== undefined)
    .map(m => `- ${SOURCE_DESC[m]}`)
    .join('\n')

const onlyA = SHIPPED_MODES.filter(m => !SHIPPED_B_MODES.includes(m))

const lines = [
  '<!-- Generated by scripts/gen-effects.mjs — do not edit; run `pnpm effects`.',
  '     The hand-written half of this page is docs/FEATURES.md. -->',
  '',
  '# Effects',
  '',
  'Every control in the app, by where it sits on the signal path, with the fault',
  'each one models. Generated from the same control table the panel renders, so',
  'it cannot fall behind the app.',
  '',
  '[Features](FEATURES.md) is the other half — what the app *is*, argued rather',
  'than enumerated. Start there for the tour.',
  '',
  'Every control carries its text below on its own **?**, and both the filter box',
  'and `ctrl+k` search it, so a fault is findable here or in the app.',
  '',
  '## Sources',
  '',
  'What either deck can be fed:',
  '',
  modeList(SHIPPED_B_MODES),
  '',
  onlyA.length === 0
    ? ''
    : `Source A additionally takes ${onlyA.map(m => SOURCE_DESC[m].split(' — ')[0]).join(', ')}; source B does not.`,
  '',
  ...PHASE_ORDER.flatMap(p => section(p, undefined, at(p))),
  ...section(
    'Source B',
    'The second deck, with its own cable ahead of the mixer, so a fault can hit one source alone.',
    at('b'),
  ),
  ...LOOP_STAGES.flatMap(l =>
    section(`${l.name} — feedback loop`, `${l.what}.`, at(l.loop)),
  ),
  ...section(
    SOUND_STAGE,
    `Hangs off ${SOUND_JOIN} — ${SOUND_BLURB}.`,
    at('audio'),
  ),
  ...section(
    VIEW_STAGE,
    `Hangs off ${VIEW_JOIN}. Viewing conditions rather than faults: nothing here is in the signal path.`,
    at('view'),
  ),
  '',
  '---',
  '',
  '[Features](FEATURES.md) — the tour · [User guide](USER-GUIDE.md) — driving it ·',
  '[How it works](HOW-IT-WORKS.md) — the code',
  '',
]

const raw = lines.join('\n').replaceAll(/\n{3,}/g, '\n\n')

await vite.close()

// Formatted here rather than left to `pnpm format`, and that is the difference
// between a check that holds and one that cries wolf: oxfmt reflows markdown,
// so a file this script emitted and a file oxfmt has since touched are not the
// same bytes, and --check would report every clean tree as stale. Generating
// what the formatter would have produced anyway settles it in one place.
// Resolved through node rather than spelled as `node_modules/.bin/oxfmt`, which
// is only there in a full checkout: a `git worktree` copy has no node_modules of
// its own, and node's own lookup walks up into the one it shares.
const require = createRequire(import.meta.url)
const oxfmtPkg = require.resolve('oxfmt/package.json')
const OXFMT = join(dirname(oxfmtPkg), require(oxfmtPkg).bin.oxfmt)
const SCRATCH = 'docs/.effects-generated.md'
const format = text => {
  writeFileSync(SCRATCH, text)
  try {
    execFileSync(OXFMT, [SCRATCH], { stdio: 'ignore' })
    return readFileSync(SCRATCH, 'utf8')
  } finally {
    rmSync(SCRATCH, { force: true })
  }
}

const out = format(raw)

if (process.argv.includes('--check')) {
  if (readFileSync(OUT, 'utf8') !== out) {
    console.error(`${OUT} is stale — run \`pnpm effects\``)
    process.exit(1)
  }
  console.log(`${OUT} is current`)
} else {
  writeFileSync(OUT, out)
  const n = GROUPS.reduce((a, g) => a + g.sliders.length, 0)
  console.log(`${OUT}: ${GROUPS.length} groups, ${n} controls`)
}
