import { describe, expect, it } from 'vitest'

import {
  ARCHIVE,
  ARCHIVE_IDS,
  archiveCaption,
  candidateOrder,
  identifiersIn,
  isArchiveId,
  queryPlan,
  renditionFrom,
  searchUrl,
} from './archive'
import { SOURCE_B_MODES, SOURCE_DESC, SOURCE_KIND, SOURCE_MODES } from './modes'

// archive.org hands back arbitrary JSON from another origin, and the reason
// these readers exist is that an item says nothing useful about itself until
// its file list is read: the same collection holds a 30-second ident with a
// 3 MB `h.264 IA` beside a two-hour tape rip whose only rendition is a 1.3 GB
// master. Everything below is a shape that actually came back from
// archive.org.

describe('renditionFrom', () => {
  // The real file list for Dusty_Trailer_December_1983, trimmed to the entries
  // that matter. Note every number arrives as a *string* — that is what the
  // API sends, and parsing it wrong is how a cap stops applying.
  const dusty = {
    files: [
      {
        name: "'Dusty' Trailer (December 1983)-FpFy3zrYE3M.autogenerated.vtt",
        format: 'Web Video Text Tracks',
        size: '467',
      },
      {
        name: "'Dusty' Trailer (December 1983)-FpFy3zrYE3M.mp4",
        format: 'h.264',
        size: '3214809',
        height: '480',
        width: '640',
        length: '30.65',
      },
      {
        name: "'Dusty' Trailer (December 1983)-FpFy3zrYE3M.ogv",
        format: 'Ogg Video',
        size: '2370817',
        height: '300',
        width: '400',
        length: '30.63',
      },
    ],
  }

  it('takes the rendition nearest the raster height', () => {
    const got = renditionFrom(dusty, 'Dusty_Trailer_December_1983')
    expect(got?.url).toContain("/cors/Dusty_Trailer_December_1983/'Dusty'")
    expect(got?.url).toContain('.mp4')
    expect(got?.title).toBe('Dusty_Trailer_December_1983')
  })

  // Only /cors/ carries an ACAO header the browser will accept; /download/ and
  // /serve/ redirect to a storage node that sends none, and the element then
  // refuses to load rather than merely tainting. Measured 2026-08-09.
  it('addresses the file through /cors/, never /download/', () => {
    const url = renditionFrom(dusty, 'Dusty_Trailer_December_1983')?.url ?? ''
    expect(url.startsWith('https://archive.org/cors/')).toBe(true)
    expect(url).not.toContain('/download/')
    expect(url).not.toContain('/serve/')
  })

  // Spaces, quotes and parentheses are ordinary in an archive.org file name. The
  // space is the one that must not survive; `'` and `()` are legal in a path and
  // encodeURIComponent leaves them, which is the form the live endpoint answered
  // 200 to.
  it('escapes a file name that is a sentence', () => {
    const url = renditionFrom(dusty, 'Dusty_Trailer_December_1983')?.url ?? ''
    expect(url).not.toContain(' ')
    expect(decodeURIComponent(url)).toContain("'Dusty' Trailer (December 1983)")
  })

  // The case that makes taking the biggest wrong: the same commercial as a 3 MB
  // derivative and an 89 MB 1440x1080 master. Both play; only one is worth a
  // wait, and after the signal path nobody could tell them apart.
  it('prefers the small derivative over the tall master', () => {
    const got = renditionFrom(
      {
        files: [
          {
            name: 'ABC-WEWS-5_1994-06-06.ia.mp4',
            format: 'h.264 IA',
            size: '3000000',
            height: '480',
            length: '29.92',
          },
          {
            name: 'mo_ABC-WEWS-5_1994-06-06.mp4',
            format: 'MPEG4',
            size: '89500000',
            height: '1080',
            length: '29.88',
          },
        ],
      },
      'CLE-B15_275681-276577',
    )
    expect(got?.url).toContain('ABC-WEWS-5_1994-06-06.ia.mp4')
  })

  // `h.264 IA` is the derivative most items actually carry. Filtering on
  // `h.264` alone — the obvious guess — matched 1 item in 5 across these pools.
  it('accepts h.264 IA, which is what most items actually hold', () => {
    const got = renditionFrom(
      {
        files: [
          {
            name: 'x.ia.mp4',
            format: 'h.264 IA',
            size: '500000',
            height: '480',
            length: '24.64',
          },
        ],
      },
      'x',
    )
    expect(got?.url).toContain('x.ia.mp4')
  })

  it('drops an item whose only rendition is over the byte cap', () => {
    expect(
      renditionFrom(
        {
          files: [
            {
              name: 'AV_Geeks_Lunch.mp4',
              format: 'MPEG4',
              size: '531500000',
              height: '480',
              length: '5355.59',
            },
          ],
        },
        'av-geeks-lunch-6-30-2020',
      ),
    ).toBeNull()
  })

  // The long channel raises its own cap, because holding a 20-minute industrial
  // film to a 30-second ident's budget does not make it arrive sooner — it makes
  // the channel empty. Prelinger measured 3 usable in 11 at the short cap, and
  // its h.264 reels run 48-57 MB, which is what the long cap is sized for.
  it('takes a rendition the short cap would have refused, on the long cap', () => {
    const film = {
      files: [
        {
          name: 'nevada.mp4',
          format: 'h.264',
          size: '52300000',
          height: '480',
          length: '1131',
        },
      ],
    }
    expect(renditionFrom(film, 'nevada')).toBeNull()
    expect(
      renditionFrom(film, 'nevada', ARCHIVE['ia-industrial'].maxBytes)?.url,
    ).toContain('nevada.mp4')
  })

  it('drops an item whose only rendition is a whole tape', () => {
    expect(
      renditionFrom(
        {
          files: [
            {
              name: 'tape.mp4',
              format: 'h.264',
              size: '9000000',
              height: '480',
              length: '7200',
            },
          ],
        },
        'some-tape',
      ),
    ).toBeNull()
  })

  // `length` is sometimes a timestamp rather than seconds. Number('1:04:12') is
  // NaN, and a NaN slipping past the duration cap is how a two-hour master gets
  // downloaded — so an unreadable duration must not read as zero.
  it('does not let an unparseable duration pass as zero', () => {
    const got = renditionFrom(
      {
        files: [
          {
            name: 'tape.mp4',
            format: 'h.264',
            size: '9000000',
            height: '480',
            length: '1:04:12',
          },
        ],
      },
      'some-tape',
    )
    // Unreadable, so the byte cap is the only thing judging it — and it passes
    // that. What must not happen is the duration being treated as satisfied by
    // a NaN comparison on a file that is genuinely two hours long *and* large.
    expect(got).not.toBeNull()
    expect(
      renditionFrom(
        {
          files: [
            {
              name: 'tape.mp4',
              format: 'h.264',
              size: '900000000',
              height: '480',
              length: '1:04:12',
            },
          ],
        },
        'some-tape',
      ),
    ).toBeNull()
  })

  // The dangerous one: archive.org renders a Theora `.ogv` for most older items
  // and it is usually the smallest file in the ladder, so the scoring would
  // reach straight for it — but browsers have removed Theora, and the element
  // does not error. It fires `loadeddata` at 0x0, and the slot shows nothing.
  it('never takes a Theora .ogv, even as the smallest thing on offer', () => {
    const got = renditionFrom(
      {
        files: [
          {
            name: 'reel.ogv',
            format: 'Ogg Video',
            size: '2000000',
            height: '300',
            length: '464',
          },
          {
            name: 'reel.mp4',
            format: 'h.264',
            size: '20000000',
            height: '480',
            length: '464',
          },
        ],
      },
      'reel',
    )
    expect(got?.url).toContain('reel.mp4')
    expect(
      renditionFrom(
        {
          files: [
            {
              name: 'reel.ogv',
              format: 'Ogg Video',
              size: '2000000',
              height: '300',
            },
          ],
        },
        'reel',
      ),
    ).toBeNull()
  })

  it('drops formats and containers no browser will play', () => {
    expect(
      renditionFrom(
        {
          files: [
            {
              name: 'x.mkv',
              format: 'Matroska',
              size: '900000',
              height: '480',
            },
            { name: 'y.mpg', format: 'MPEG2', size: '900000', height: '480' },
            { name: 'z.gif', format: 'Animated GIF', size: '90000' },
          ],
        },
        'x',
      ),
    ).toBeNull()
  })

  // A format this list allows on a container it does not — seen as `MPEG4` on
  // `.mkv`, which would load as nothing.
  it('trusts the extension over the format label', () => {
    expect(
      renditionFrom(
        { files: [{ name: 'x.mkv', format: 'MPEG4', size: '900000' }] },
        'x',
      ),
    ).toBeNull()
  })

  it('drops an item with no files list at all', () => {
    expect(renditionFrom({}, 'x')).toBeNull()
    expect(renditionFrom({ files: [] }, 'x')).toBeNull()
    expect(renditionFrom(null, 'x')).toBeNull()
    expect(renditionFrom({ files: 'nope' }, 'x')).toBeNull()
  })

  // Height is missing on some entries. Those still play, and dropping them
  // loses whole items whose only rendition happens to be under-described.
  it('keeps a rendition that will not say how tall it is', () => {
    const got = renditionFrom(
      { files: [{ name: 'x.mp4', format: 'h.264', size: '900000' }] },
      'x',
    )
    expect(got?.url).toContain('x.mp4')
  })

  it('drops a rendition too small to be worth the raster', () => {
    expect(
      renditionFrom(
        {
          files: [
            { name: 'x.mp4', format: 'h.264', size: '90000', height: '120' },
          ],
        },
        'x',
      ),
    ).toBeNull()
  })

  it('carries the item page, which is where the credit is', () => {
    const got = renditionFrom(dusty, 'Dusty_Trailer_December_1983')
    expect(got?.page).toBe(
      'https://archive.org/details/Dusty_Trailer_December_1983',
    )
  })
})

describe('identifiersIn', () => {
  it('reads the identifiers a search came back with', () => {
    expect(
      identifiersIn({
        response: {
          numFound: 16617,
          docs: [{ identifier: 'a' }, { identifier: 'b' }],
        },
      }),
    ).toEqual(['a', 'b'])
  })

  it('reads nothing out of a shape that is not a search result', () => {
    expect(identifiersIn({})).toEqual([])
    expect(identifiersIn({ response: {} })).toEqual([])
    expect(
      identifiersIn({ response: { docs: [{}, { identifier: 3 }] } }),
    ).toEqual([])
    expect(identifiersIn(null)).toEqual([])
  })
})

describe('candidateOrder', () => {
  it('puts aside the clip already on the slot', () => {
    expect(candidateOrder(['a', 'b', 'c'], 'b')).toEqual(['a', 'c'])
  })

  // A pool that has genuinely narrowed to one item is not a failed roll.
  it('yields rather than empties when the pool holds only that one', () => {
    expect(candidateOrder(['a'], 'a')).toEqual(['a'])
  })

  it('has nothing to avoid on a channel the slot was not already on', () => {
    expect(candidateOrder(['a', 'b'], '')).toEqual(['a', 'b'])
  })
})

describe('queryPlan', () => {
  it('starts at the offset it was given', () => {
    expect(queryPlan(['x', 'y'], 0)).toBe('x')
    expect(queryPlan(['x', 'y'], 1)).toBe('y')
  })

  it('says nothing for a channel with no pools', () => {
    expect(queryPlan([], 0)).toBe('')
  })
})

// archive.org's `sort[]=random` is stably seeded — the same query returns the
// same order forever — so the page is what makes a channel a pool rather than a
// fixed clip. That is easy to "tidy" away, hence a test on the url itself.
describe('searchUrl', () => {
  it('asks for a page, so two rolls do not see the same dozen', () => {
    const one = new URL(searchUrl('collection:vhsopenings', 7))
    expect(one.searchParams.get('page')).toBe('7')
    expect(one.searchParams.get('sort[]')).toBe('random')
    expect(
      new URL(searchUrl('collection:vhsopenings', 8)).searchParams.get('page'),
    ).toBe('8')
  })

  it('narrows to movies and asks only for identifiers', () => {
    const url = new URL(searchUrl('collection:prelinger', 1))
    expect(url.searchParams.get('q')).toBe(
      'collection:prelinger AND mediatype:movies',
    )
    expect(url.searchParams.get('fl[]')).toBe('identifier')
    expect(url.searchParams.get('output')).toBe('json')
  })
})

describe('archiveCaption', () => {
  it('reads a slug as words', () => {
    expect(archiveCaption('gold-key-entertainment-logo-1971-1980')).toBe(
      'gold key entertainment logo 1971 1980',
    )
    expect(archiveCaption('Dusty_Trailer_December_1983')).toBe(
      'Dusty Trailer December 1983',
    )
  })

  // archive.org's de-duplicator appends a date to a re-used identifier, which
  // says nothing to anyone reading a caption.
  it('drops the de-duplicator suffix', () => {
    expect(archiveCaption('the-lion-king-1995-vhs_202412')).toBe(
      'the lion king 1995 vhs',
    )
  })
})

describe('channels', () => {
  it('every id has a channel, a label, a pool and a download budget', () => {
    for (const id of ARCHIVE_IDS) {
      const channel = ARCHIVE[id]
      expect(channel.label.length).toBeGreaterThan(0)
      expect(channel.queries.length).toBeGreaterThan(0)
      expect(channel.maxBytes).toBeGreaterThan(0)
    }
  })

  it('recognises its own ids and nothing else', () => {
    for (const id of ARCHIVE_IDS) expect(isArchiveId(id)).toBe(true)
    expect(isArchiveId('wiki-retro')).toBe(false)
    expect(isArchiveId('bars')).toBe(false)
  })

  // Same line controls.test.ts holds for a control's `place`: a channel added
  // to ARCHIVE_IDS has to be offered by both pickers and banded, or this fails
  // rather than the option quietly going missing from one of them.
  it('is offered by both pickers, described, and banded as archive', () => {
    for (const id of ARCHIVE_IDS) {
      expect(SOURCE_MODES).toContain(id)
      expect(SOURCE_B_MODES).toContain(id)
      expect(SOURCE_DESC[id]).toBe(ARCHIVE[id].label)
      expect(SOURCE_KIND[id]).toBe('archive')
    }
  })
})
